name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    name: Setup Node.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup  # Dependência do job de configuração

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test  # Só roda deploy se os testes passarem
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Executa apenas na main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: npm run start  # Se precisar de um build antes do deploy

      - name: Deploy application
        run: echo "Deploy realizado com sucesso na branch main!"  # Aqui entra seu comando de deploy real
