name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  setup:
    name: Setup Node.js and MongoDB
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      - name: Start MongoDB
        run: docker-compose up -d
        working-directory: ./ # Certifique-se de que o docker-compose.yaml está na raiz do seu repositório

      - name: Wait for MongoDB to start
        run: sleep 10 # Ajuste o tempo conforme necessário

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: setup  # Dependência do job de configuração

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Start MongoDB
        run: docker-compose up -d
        working-directory: ./ # Certifique-se de que o docker-compose.yaml está na raiz do seu repositório

      - name: Wait for MongoDB to start
        run: sleep 10 # Ajuste o tempo conforme necessário

      - name: Run tests
        run: npm run

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: test  # Só roda deploy se os testes passarem
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'  # Executa apenas na main

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build project
        run: npm run start  # Se precisar de um build antes do deploy

      - name: Deploy application
        run: echo "Deploy realizado com sucesso na branch main!"  # Aqui entra seu comando de deploy real
